export const FETCH_STUDENT_PROFILE = 'FETCH_STUDENT_PROFILE';
export const UPDATE_STUDENT_PROFILE = 'UPDATE_STUDENT_PROFILE';

export const FETCH_STUDENT_PASSWORD = 'FETCH_STUDENT_PASSWORD';
export const CHANGE_STUDENT_PASSWORD = 'CHANGE_STUDENT_PASSWORD';

export const FETCH_STUDENT_AVATAR = 'FETCH_STUDENT_AVATAR';
export const POST_STUDENT_AVATAR = 'POST_STUDENT_AVATAR';

export const FETCH_STUDENT_HOCKYTACNGHIEP = 'FETCH_STUDENT_HOCKYTACNGHIEP';
export const POST_STUDENT_HOCKYTACNGHIEP = 'POST_STUDENT_HOCKYTACNGHIEP';

export const FETCH_STUDENT_THOIKHOABIEU = 'FETCH_STUDENT_THOIKHOABIEU';

export const FETCH_LIST_TEACHERS = 'FETCH_LIST_TEACHERS';

export const GET_TOKEN = 'GET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';