export const FETCH_STUDENT_PROFILE = 'FETCH_STUDENT_PROFILE';
export const UPDATE_STUDENT_PROFILE = 'UPDATE_STUDENT_PROFILE';

export const GET_TOKEN = 'GET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';